# Generated by Django 4.1.6 on 2023-02-07 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('1', 'Мужской'), ('2', 'Женский')], default='1', max_length=1, verbose_name='Пол'),
        ),
    ]
